name: Link Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 1"

jobs:
  link-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check links
        uses: lycheeverse/lychee-action@v2.3.0
        with:
          args: --verbose --no-progress './**/*.md'
          fail: true
